### ISSUE TITLE
Prefix for the machine translation formality task

### ISSUE THREAD

**Issue by jackjyzhang** [yangkevin2/naacl-2021-fudge-controlled-generation#5]
Hello! I have a question about how the data is constructed for the machine translation formality task. For all other tasks, the discriminator is trained using a prefix of data <img src="https://render.githubusercontent.com/render/math?math=x_{1:i}">, but I noticed that in the paper section 4.3.1 FUDGE instantiation the formality classifier is trained using a "prefix" <img src="https://render.githubusercontent.com/render/math?math=x_{1:n}">, and in the [code](https://github.com/yangkevin2/naacl-2021-fudge-controlled-generation/blob/fbedf820c306c5b3cbf684dc414b2464fc603222/data.py#L272) I can see that `post_to_split` is always equal to `length` so the full formal/informal sentence is always used. I was wondering why is it the case only for the formality task. Doesn't this mean the classifier is not learning to "predict the future"? Thanks for your help in advance.

**Comment by yangkevin2** [comment]
Hi, 

Thanks for asking. Sorry, the paper should say x_1:i rather than x_1:n. 

As for the code, I didn't document this very well and will add a comment. In the formality task, the data loader is returning the full sequence, due to an efficiency optimization in training where we run a unidirectional RNN over the full sequence to get the loss at each position (i.e., simultaneously training over all the possible prefixes in the sentence).

**Comment by jackjyzhang** [comment]
Thanks for the explanation! I understand it now.
